#local
#spring.datasource.url=jdbc:sqlite:E:\\projects\\java\\screenerdb\\stockdata.db?foreign_keys=on&journal_mode=WAL&busy_timeout=5000
#jdbc:h2:tcp://localhost/~/mydb;CACHE_SIZE=131072
spring.datasource.url=jdbc:h2:tcp://localhost:9092/E:/projects/java/screenerdb/screenerData;CACHE_SIZE=65536;LOCK_TIMEOUT=10000

#test machine
#spring.datasource.url=jdbc:sqlite:E:\\projects\\java\\screenerdb\\stockdata.db

#spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect

#working conf
#spring.datasource.driver-class-name=org.sqlite.JDBC
#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
#spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# HikariCP pool settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=H2Pool

external.api.url=https://service.upstox.com/chart/open/v3/candles

stock.processor.enabled=true
stock.processor.interval.minutes=5
stock.processor.low-priority.interval.minutes=10
stock.processor.low-priority.mode=repeat

#this URL does not require auth token.
scanx.api.url=https://ow-scanx-analytics.dhan.co/customscan/fetchdt

#if the above one doesn't work use below URL (needs auth token). you can get 
#auth token by creating account in scanx.trade website provided by "Dhan" broker.
#scanx.api.url=https://scanx-analytics.dhan.co/customscan/v2/fetchdt